# Generated by Django 5.0.4 on 2024-05-26 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_advertise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='advertise',
            name='location',
        ),
        migrations.AlterField(
            model_name='advertise',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.images'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.images'),
        ),
    ]
