# Generated by Django 5.0.4 on 2024-05-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_images_remove_advertise_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='content',
            field=models.BinaryField(editable=True),
        ),
    ]
