# Generated by Django 5.0.4 on 2024-05-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_alter_images_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertise',
            name='location',
            field=models.CharField(default='main', max_length=100, null=True),
        ),
    ]
