# Generated by Django 5.0.4 on 2024-05-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('vendor_panel', '0005_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_panel.vendorservice'),
        ),
    ]
